### ISSUE TITLE
Reached maximum number of characters for languagetool

### ISSUE THREAD

**Issue by flaxel** [reviewdog/action-languagetool#26]
When I run the Github Action, I get the following error message:

```
reviewdog: post failed for LanguageTool: failed to post result: PATCH https://api.github.com/repos/<company/user>/>repository>/check-runs/2296919823: 422 Invalid request.

Only 65535 characters are allowed; 68794 were supplied. []
```

The problem is related to the Github API. There is already an [existing discussion](https://github.community/t/undocumented-65535-character-limit-on-requests/117564) about it, but it seems that the problem is not solved immediately. Is there a workaround to fix this problem in the action?

**Comment by shogo82148** [comment]
reviewdog supports some reporters for GitHub.

- [github-pr-check](https://github.com/reviewdog/reviewdog#reporter-github-checks--reportergithub-pr-check)
- [github-check](https://github.com/reviewdog/reviewdog#reporter-github-checks--reportergithub-check)
- [github-pr-review](https://github.com/reviewdog/reviewdog#reporter-github-pullrequest-review-comment--reportergithub-pr-review)

Did you try the other reporters?

**Comment by flaxel** [comment]
Oh thank you for the tip. It worked with the reporter `github-pr-review`. I have not tested the others. 

If you want, the issue can be closed, unless you want to continue working on the problem
